[ 2024-06-23 12:23:00,941 ] 58 datasets - INFO - PyTorch version 2.3.1 available.
[ 2024-06-23 12:23:01,765 ] 12 root - INFO - >>>>>> stage Data Ingestion stage started <<<<<<
[ 2024-06-23 12:23:01,767 ] 49 root - INFO - yaml file: config/config.yaml loaded successfully
[ 2024-06-23 12:23:01,767 ] 49 root - INFO - yaml file: params.yaml loaded successfully
[ 2024-06-23 12:23:01,767 ] 69 root - INFO - created directory at: artifacts
[ 2024-06-23 12:23:01,767 ] 69 root - INFO - created directory at: artifacts/data_ingestion
[ 2024-06-23 12:23:01,767 ] 25 root - INFO - File already exists of size: ~ 7718 KB
[ 2024-06-23 12:23:01,812 ] 15 root - INFO - >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x
[ 2024-06-23 12:23:01,812 ] 25 root - INFO - >>>>>> stage Data Validation stage started <<<<<<
[ 2024-06-23 12:23:01,814 ] 49 root - INFO - yaml file: config/config.yaml loaded successfully
[ 2024-06-23 12:23:01,814 ] 49 root - INFO - yaml file: params.yaml loaded successfully
[ 2024-06-23 12:23:01,815 ] 69 root - INFO - created directory at: artifacts
[ 2024-06-23 12:23:01,815 ] 69 root - INFO - created directory at: artifacts/data_validation
[ 2024-06-23 12:23:01,819 ] 28 root - INFO - >>>>>> stage Data Validation stage completed <<<<<<

x==========x
[ 2024-06-23 12:23:01,819 ] 37 root - INFO - >>>>>> stage Data Transformation stage started <<<<<<
[ 2024-06-23 12:23:01,820 ] 49 root - INFO - yaml file: config/config.yaml loaded successfully
[ 2024-06-23 12:23:01,821 ] 49 root - INFO - yaml file: params.yaml loaded successfully
[ 2024-06-23 12:23:01,821 ] 69 root - INFO - created directory at: artifacts
[ 2024-06-23 12:23:01,821 ] 69 root - INFO - created directory at: artifacts/data_transformation
[ 2024-06-23 12:23:02,678 ] 40 root - INFO - >>>>>> stage Data Transformation stage completed <<<<<<

x==========x
[ 2024-06-23 12:23:02,678 ] 49 root - INFO - *******************
[ 2024-06-23 12:23:02,678 ] 50 root - INFO - >>>>>> stage Model Trainer stage started <<<<<<
[ 2024-06-23 12:23:02,680 ] 49 root - INFO - yaml file: config/config.yaml loaded successfully
[ 2024-06-23 12:23:02,680 ] 49 root - INFO - yaml file: params.yaml loaded successfully
[ 2024-06-23 12:23:02,681 ] 69 root - INFO - created directory at: artifacts
[ 2024-06-23 12:23:02,681 ] 69 root - INFO - created directory at: artifacts/model_trainer
[ 2024-06-23 12:23:22,253 ] 55 root - ERROR - MPS backend out of memory (MPS allocated: 9.48 GB, other allocations: 10.64 GB, max allowed: 20.40 GB). Tried to allocate 375.40 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Traceback (most recent call last):
  File "/Users/Aadish/Documents/textSummarizer/main.py", line 52, in <module>
    model_trainer.main()
  File "/Users/Aadish/Documents/textSummarizer/src/textSummarizer/pipeline/stage_4_model_trainer.py", line 15, in main
    model_trainer_config.train()
  File "/Users/Aadish/Documents/textSummarizer/src/textSummarizer/conponents/model_trainer.py", line 48, in train
    trainer.train()
  File "/Users/Aadish/Documents/textsummarizer/venv/lib/python3.9/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/Users/Aadish/Documents/textsummarizer/venv/lib/python3.9/site-packages/transformers/trainer.py", line 2216, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/Users/Aadish/Documents/textsummarizer/venv/lib/python3.9/site-packages/transformers/trainer.py", line 3250, in training_step
    self.accelerator.backward(loss)
  File "/Users/Aadish/Documents/textsummarizer/venv/lib/python3.9/site-packages/accelerate/accelerator.py", line 2134, in backward
    loss.backward(**kwargs)
  File "/Users/Aadish/Documents/textsummarizer/venv/lib/python3.9/site-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/Users/Aadish/Documents/textsummarizer/venv/lib/python3.9/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/Users/Aadish/Documents/textsummarizer/venv/lib/python3.9/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: MPS backend out of memory (MPS allocated: 9.48 GB, other allocations: 10.64 GB, max allowed: 20.40 GB). Tried to allocate 375.40 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
